# This is a basic workflow to help you get started with Actions

name: Vue.js

on:
  push:
    branches: [ vue ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:
      - uses: actions/setup-node@v2

      # Runs a set of commands using the runners shell
      - name: Build Vue app.
        run: |
          yarn --cwd vue-templater/ install
          yarn --cwd vue-templater/ build --dest docs/vue/
