# This is a basic workflow to help you get started with Actions

name: Vue.js

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:
      - uses: actions/setup-node@v2

      # Runs a set of commands using the runners shell
      - name: Build Vue app.
        working-directory: vue-templater
        run: |
          ls
          ls ..
          yarn build --dest ../docs/vue/
