# This is a basic workflow to help you get started with Actions

name: Vue.js

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2

      # Runs a set of commands using the runners shell
      - name: Build Vue app.
        working-directory: vue-templater
        run: yarn build --dest ../docs/vue/
