# This is a basic workflow to help you get started with Actions

name: Vue.js

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: npm update

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd vue-templater
          yarn build --dest ../docs/vue/
